import uuid
from dataclasses import dataclass
from datetime import date
from typing import Literal

from app.bootstrap.unit_of_work import AppUnitOfWork
from app.business.domain.exceptions import BusinessNotFoundException
from app.dashboard.application.pdf_generator import generate_profit_loss_pdf
from app.dashboard.application.queries.get_dashboard_trend import (
    GetDashboardTrendQuery,
    GetDashboardTrendUseCase,
)
from app.shared.application.ports import EmailAttachment, IEmailSender


@dataclass(frozen=True)
class SendReportEmailCommand:
    business_id: uuid.UUID
    recipient_email: str
    start_date: date
    end_date: date
    granularity: Literal["day", "week", "month"] | None = None


class SendReportEmailUseCase:
    """Emails the Profit & Loss PDF (Slice 4's generate_profit_loss_pdf) as
    an attachment. Runs synchronously within the request rather than via
    the outbox/Celery relay used for UserRegistered -> verification email —
    this is a direct, user-initiated "send now" click expecting immediate
    success/failure feedback, not a decoupled reaction to a domain event.
    """

    def __init__(self, uow: AppUnitOfWork, email_sender: IEmailSender) -> None:
        self._uow = uow
        self._email_sender = email_sender

    async def execute(self, command: SendReportEmailCommand) -> None:
        business = await self._uow.businesses.get_by_id(command.business_id)
        if business is None:
            raise BusinessNotFoundException(f"Business {command.business_id} not found")

        trend = await GetDashboardTrendUseCase(self._uow).execute(
            GetDashboardTrendQuery(
                business_id=command.business_id,
                start_date=command.start_date,
                end_date=command.end_date,
                granularity=command.granularity,
            )
        )
        pdf_bytes = generate_profit_loss_pdf(business.name, trend)

        await self._email_sender.send(
            to=command.recipient_email,
            subject=f"{business.name} — Profit & Loss Report",
            body=(
                f"Hi,\n\nAttached is the Profit & Loss report for {business.name} "
                f"covering {command.start_date.isoformat()} to {command.end_date.isoformat()}.\n\n"
                "This report was generated by FinanceAI."
            ),
            attachments=[
                EmailAttachment(
                    filename=f"profit-loss-{trend.granularity}.pdf",
                    content=pdf_bytes,
                    content_type="application/pdf",
                )
            ],
        )
